- name: install some packages
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common
    - dirmngr
    - sudo
    - python-mysqldb

- name: create youPHPtube database
  mysql_db: 
    db: youPHPTube 
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'

- name: create user youphptube
  mysql_user: 
    name: youphptube
    password: passw0rd
    priv: 'youPHPTube.*:ALL,GRANT'
    host: localhost
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'

- name: create youPHPTubeEncoder database
  mysql_db: 
    db: youPHPTube-Encoder 
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'

- name: create user youPHPTubeEncoder
  mysql_user: 
    name: youphptubeencoder
    password: passw0rd
    priv: 'youPHPTube-Encoder.*:ALL,GRANT'      
    host: localhost
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - apache2
    - php
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-gd
    - php-intl
    - mysql-client
    - ffmpeg
    - git
    - libimage-exiftool-perl
    - python

- name: get youPHPtube
  git:
    repo: '{{ youphptube_repo_url }}'
    dest: '{{ doc_root }}/{{ youphptube_directory }}'
    clone: yes

- name: get youPHPTubeEncoder
  git:
    repo: '{{ youphptube_encoder_repo_url }}'
    dest: '{{ doc_root }}/{{ youphptube_encoder_directory }}'
    clone: yes

- name: get youtube-dl and set rights
  command: "{{ item }}" 
  with_items:
    - curl -L https://youtube-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
    - chmod a+rx /usr/local/bin/youtube-dl
    - a2enmod rewrite

- name: create folder videos in youPHPtube
  file:
    path: '{{ doc_root }}/{{ youphptube_directory }}/videos'
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: create folder videos in youPHPTubeEncoder
  file:
    path: '{{ doc_root }}/{{ youphptube_encoder_directory }}/videos'
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: modify php.ini
  lineinfile:
    dest: "{{ item.dest}}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - {dest: '/etc/php/7.2/apache2/php.ini', regexp: 'post_max_size = 8M', line: 'post_max_size = 1000M'}
    - {dest: '/etc/php/7.2/apache2/php.ini', regexp: 'upload_max_filesize = 2M', line: 'upload_max_filesize = 1000M'}
    - {dest: '/etc/php/7.2/apache2/php.ini', regexp: 'max_execution_time = 30', line: 'max_execution_time = 7200'}
    - {dest: '/etc/php/7.2/apache2/php.ini', regexp: 'memory_limit = 128M', line: 'memory_limit = 512M'}

- name: Install /etc/{{ apache_config_dir }}/youphptube.conf from template
  template:
    src: youphptube.conf.j2
    dest: "/etc/{{ apache_config_dir }}/youphptube.conf"

- name: Symlink /etc/apache2/sites-enabled/youphptube.conf to /etc/apache2/sites-available/youphptube.conf if youphptube_enabled
  file:
    src: /etc/apache2/sites-available/youphptube.conf
    path: /etc/apache2/sites-enabled/youphptube.conf
    state: link
  when: youphptube_enabled

- name: Remove symlink /etc/apache2/sites-enabled/youphptube.conf if not youphptube_enabled
  file:
    path: /etc/apache2/sites-enabled/youphptube.conf
    state: absent
  when: not youphptube_enabled

- name: Restart Apache ({{ apache_service }}) to enable/disable YouPHPTube
  systemd:
    name: "{{ apache_service }}"
    state: restarted
